# Generated by Django 3.0.8 on 2020-07-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=150)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SentBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_itms', to='campaign.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=20)),
                ('sender', models.CharField(choices=[('GP', 'Grameen Phone'), ('BL', 'Banglalink'), ('TT', 'Tele Talk'), ('RB', 'Robi')], max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaign.Campaign')),
            ],
        ),
    ]
